### ISSUE TITLE
Table 5

### ISSUE THREAD

**Issue by vasishth** [vasishth/BayesLMMTutorial#3]
This Table was supposed to have a correlation parameter (a reviewer pointed this out), but we didn't put it in. This should be added.

**Comment by vasishth** [comment]
Actually, two correlation parameters.

**Comment by TannerSorensen** [comment]
Sven added these rows. I added the clarification to explain why we do not report Rhat for correlation parameters:

"\footnote{We do not report $\hat R$ for parameters $\rho _u$, $\rho _w$ because these parameters converge when $\hat R$ equals one for each entry of the matrices $L_u$, $L_w$. This was the case.}"
