### ISSUE TITLE
lmer fit

### ISSUE THREAD

**Issue by vasishth** [vasishth/BayesLMMTutorial#4]
Since we don't show the lmer fit, the reader cannot know that the correlations are +1 and -1. Yet we say:

"However, the classical LMM is overparameterized due to an insufficient number of data points. Hence, correlations between random effects could not be estimated, as indicated by perfect correlations of $-1$ and $1$."

I would show the lmer fit and the Stan fit for all variance components side by side (e.g., in Table 5). In Nicenboim and Vasishth 2016 I think we did this.

**Comment by TannerSorensen** [comment]
I changed the text from 

"However, the classical LMM is overparameterized due to an insufficient number of data points. Hence, correlations between random effects could not be estimated, as indicated by perfect correlations of $-1$ and $1$."

to

"However, the classical LMM is overparameterized due to an insufficient number of data points. When fit to the Gibson & Wu data, the correlation parameters are estimated as $-1$ and $1$. This means that correlations between random effects could not be estimated, as these are perfect correlations."

We do not have to describe the lmer fit, which is not the focus of the paper. But the revised text reports the correlation parameter estimates (in the sense that we make a declarative statement about their values).

**Comment by vasishth** [comment]
I edited this a bit.
